# Generated by Django 4.2.5 on 2023-09-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='intruduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shortin', models.CharField(max_length=100)),
                ('intruduce', models.CharField(max_length=500)),
                ('likecount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('intru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thumbs_up.intruduce')),
            ],
        ),
    ]
