# Generated by Django 3.2.20 on 2023-09-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs_up', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intruduce',
            name='loc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='intruduce',
            name='x',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='intruduce',
            name='y',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
