# Generated by Django 3.2.20 on 2023-09-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs_up', '0002_auto_20230918_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='intruduce',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
