# Generated by Django 3.2.20 on 2023-09-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs_up', '0004_alter_intruduce_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='intruduce',
            name='imagecheack',
            field=models.IntegerField(null=True),
        ),
    ]
