# Generated by Django 4.2.5 on 2023-09-27 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("thumbs_up", "0006_alter_intruduce_imagecheack"),
    ]

    operations = [
        migrations.DeleteModel(
            name="menu",
        ),
    ]
