# Generated by Django 4.2.4 on 2023-09-16 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guest_book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="created",
        ),
    ]
