# Generated by Django 4.2.4 on 2023-09-16 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("guest_book", "0002_remove_comments_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="comment",
            field=models.TextField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="comments",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comments",
            name="nickname",
            field=models.CharField(default="", max_length=30),
        ),
    ]
